version: '3'
services:
  userstore:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  
  