version: 1.0

services:
  userstore:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    dbname: blockchain

config:
  jwtSecret: helloworld
  account:
    confirmation:
      expiryDuration: 24h 

  